export default function home() {
  const about = "Nepal is a cultural melting pot and its arts date back to ancient times. Religion, social conditions, political climate, and various events such as natural disasters and others have influenced arts in Nepal for a long time. Nepali arts are related to religious and cultural practices. Paintings, sculptures, woodcarving, pottery and architecture are major forms of Nepali arts. Traditional art here includes intricate floral patterns, mythical beings, and the complex fusion of Hindu, Buddhist, and indigenous elements using various materials like wood, stone, metal, and cloth. Even a small temple often contains struts, tympanums, and door facades with many details. Art History Tracker occupies a unique position in a web-based platform because of its focus on Nepali artistic practices and traditions. The website houses a collection of Nepali art that covers both its religious traditions and more recent secular manifestations. Through regular updates, it explores the historic and cultural influences on Nepali art practices to encourage a better understanding, appreciation and promotion of Nepali art and artists. There have been some cases of art studies occurring in Nepal, especially in the local context. But very little has been done to theorize its study in terms of criticism and history. Art History Tracker introduces audiences to multiple perspectives and ways of interacting with culture, so they can find what resonates with them. It is difficult for the government to preserve the monuments and arts of every level, let alone promote them by digitizing the datas collected from them. That being said, there exists a void among the art community who face obstacles while exploring Nepali arts online which has led us to the creation of this site. It is important to preserve artifacts from historical events so we can remember, learn about and honor those who were involved. This place encompasses documentation, conservation and preservation of the country's artistic heritage, with the aim to both maintain and expand our identity. At Art History Tracker, we aim to create a creative space that uses art to uplift emerging Nepali artists while engaging with our surrounding environment through an accessible, communicative and collaborative exchange. We look forward to being not just an online space to look into for arts but a home to our diverse and transcultural family of artists. "
  return (
    <div style={{padding:"20px"}}>
      <h1>about</h1>
      <p>{about}</p>
    </div>
  )
}
